name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  tests:
    container: golang:alpine
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: apk --no-cache add bash curl gcc git musl-dev
      - name: Check out the target branch
        uses: actions/checkout@v2
      - name: Get dependencies
        run: go get ./...
      - name: Build the thing
        run: go build .
      - name: Run tests
        run: go test ./... -count 1 -cover -coverprofile ./profile -coverpkg ./...
      - name: Publish coverage
        if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
        uses: codecov/codecov-action@v1
        with:
          files: ./profile
          fail_ci_if_error: true
